### ISSUE TITLE
Add localheinz's PHPStan rules

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/toolbox#38]
https://github.com/localheinz/phpstan-rules

**Comment by jakzal** [comment]
I'd be careful with adding too many extensions. Currently the build is failing due to one of them: https://travis-ci.com/jakzal/toolbox/jobs/170814684#L959

I think it's best if we support well maintained (preferably official) extensions only, and let people install additional ones in their own images.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/190447/51284571-d696fa00-19e3-11e9-80a0-16fae58ecf93.png">

**Comment by jakzal** [comment]
So the question is, is this an extension worth supporting?

**Comment by dkarlovi** [comment]
Maybe we can figure out a way to separate officially supported from unofficial? Separate namespace and `unofficial` tags?

The way I see it, having these extensions for PHPStan (and later Psalm, etc) will bring significant additional value to the project since they'll be a valuable part of the toolbox. I see value in having a workflow ready which expects for them to trail for a bit behind the official release, they should be considered "best effort" if they do.
